### ISSUE TITLE
Release 1 - IndexOutOfRange Exception

### ISSUE THREAD

**Issue by Deltact** [ceyhunveyselism/c-term#1]
Using the executable provided in the releases, current release being b12-v1.5.5 the terminal gives an exception on start.
![image](https://user-images.githubusercontent.com/92210959/227813001-bdb1e59f-f597-403c-9b7a-53722b94d5e8.png)
The terminal window remains open for a few seconds before closing. There wasn't an opportunity to input anything in the console window.
Restarting proves futile.

**Comment by moonfloww** [comment]
Will fix on the next build.

**Comment by moonfloww** [comment]
For anyone looking into this issue - This is caused by the getUses() function using `specific.Length - specific.Length + 1` instead of `specific.Length - 1`. This is an easy fix, I'm not sure what made me think to put `specific.Length` twice.
