### ISSUE TITLE
b11-v1.4.5 - (Slow)Print doesn't account for spaces or newlines

### ISSUE THREAD

**Issue by Deltact** [ceyhunveyselism/c-term#2]
Basic special character support is a requirement in print commands.
One of the noticeable lacking features is white space support, clearly displayed in the first expression.
![image](https://user-images.githubusercontent.com/92210959/227813632-ca66910a-4d48-4a65-b3da-285a51fb6305.png)
The second command attempts to use a more obscure but equally useful feature in text, newlines `\n` which it also lacks support in.
![image](https://user-images.githubusercontent.com/92210959/227813969-a79a830d-d2f7-4c1d-8e92-f8c92148a668.png)
Newline support is also lacking in the basic print command.

There are many special keywords that can be used in text such as carriage return `\r` but that's not as important to be implemented if at all currently.

**Comment by moonfloww** [comment]
I would need to change the page number (see [this](https://learn.microsoft.com/en-us/windows/console/console-code-pages) for more info) to actually allow unicode characters in the console which is extremely unreliable by my previous experience of attempting to use them and this will not be fixed. However, the \n support should be implemented (I'm not sure why it doesn't work).

**Comment by moonfloww** [comment]
After checking, you specify that this is an issue with the v1.4.5 version which is not the latest version. Further commits after b11 fixes this issue.

**Comment by moonfloww** [comment]
As further investigation of the current newest build of c-term, the slowprint command actually does not use all arguments instead only printing the first word given. This will be resolved in v2.0.0.
